[build]
  base = "/astro-ui"
  command = "npm run build"
  publish = ".next"


[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.9.0"
  NEXT_PRIVATE_SKIP_TURBOPACK = "1"
  